dist: xenial

language: python

python:
  - "3.7"
  - "3.8"

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - coverage run --source=heatshrink2 setup.py test
  - make test-sdist
  - PYTHONPATH=. python scripts/benchmark.py
  - make fuzz FUZZ_TIME=1

after_success:
  - coveralls
